stages:
    - setup
    - bundle
    - deploy

include:
  - project: 'web/core/proton-config'
    ref: master
    file: '/_templates-ci/config.gitlab-ci.yml'

  - project: 'web/core/proton-config'
    ref: master
    file: '/_templates-ci/setup.gitlab-ci.yml'

bundle:
    stage: bundle
    script:
        - ./ci-scripts/v2/bundle main
    artifacts:
        expire_in: 1 days
        paths:
            - webapp-bundle.tar.gz
            - node_modules
            - appConfig.json
            - package.json
            - .env

publish:
    services:
        - docker:stable-dind
    cache: {}
    stage: deploy
    interruptible: true
    needs:
        - job: bundle
          artifacts: true
    script:
        - apt-get install -y apt-transport-https ca-certificates curl gnupg2 software-properties-common
        - curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
        - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
        - apt-get update && apt-get install -y docker-ce-cli
        # - ./ci-scripts/v2/docker make
        # The scripts below are here temporarily. I'll move them to fe-scripts after they are proven to work.
        # 1. Build
        - mkdir -p dist
        - tar xzf webapp-bundle.tar.gz -C dist
        - export DIST_IMAGE_SHA="gcr.io/proton-dev-ops/fe/mail:commit-${CI_COMMIT_SHORT_SHA}"
        - export DIST_IMAGE_REF="gcr.io/proton-dev-ops/fe/mail:branch-${CI_COMMIT_REF_SLUG}"
        - (set -x && docker build . -f ./docker/Dockerfile.dist -t "${DIST_IMAGE_SHA}" -t "${DIST_IMAGE_REF}")
        # 2. Publish images
        - git clone "https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.protontech.ch/proton/devops/test-infra.git" --depth 1
        - ./test-infra/docker-login-gcr.sh
        - docker push "${DIST_IMAGE_SHA}"
        - docker push "${DIST_IMAGE_REF}"
        # 3. Deploy
        # TODO: update test-infra to be able to get proton-mail deployed independently from proton-calendar
        # - ./test-infra/kube-install-bins.sh
        # - ./test-infra/kube-deploy.sh -a=?? -i="${DIST_IMAGE_SHA}" -b="${CI_COMMIT_REF_NAME}" --update-gitlab-status

variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: '' # disable TLS
    SERVICE_PORT_2376_TCP_PORT: 2375 # https://gitlab.com/gitlab-org/gitlab-runner/issues/4635#note_204682505
