stages:
    - setup
    - bundle
    - deploy

include:
  - project: 'web/core/proton-config'
    ref: master
    file: '/_templates-ci/config.gitlab-ci.yml'

  - project: 'web/core/proton-config'
    ref: master
    file: '/_templates-ci/setup.gitlab-ci.yml'

bundle:
    stage: bundle
    script:
        - ./ci-scripts/v2/bundle main
    artifacts:
        expire_in: 1 days
        paths:
            - webapp-bundle.tar.gz
            - node_modules
            - appConfig.json
            - package.json
            - .env

publish:
    services:
        - docker:stable-dind
    cache: {}
    stage: deploy
    interruptible: true
    needs:
        - job: bundle
          artifacts: true
    script:
        - apt-get install -y apt-transport-https ca-certificates curl gnupg2 software-properties-common
        - curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
        - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
        - apt-get update && apt-get install -y docker-ce-cli
        - ./ci-scripts/v2/docker make
