version: "3.7"

services:
  web:
    # You can either pull or rebuild if you generate a webapp-bundle.tar.gz first
    image: gcr.io/proton-dev-ops/web/mail/proton-mail:branch-develop
    build:
      context: .
    environment:
      # Feel free to change any of these values on your local .env file
      API_ENDPOINT:
      BASE_OTHER_FE_APPS:
      CALENDAR_ENDPOINT:
      CONTACTS_ENDPOINT:
      SETTINGS_ENDPOINT:
    ports:
      - 80:80
      - 443:443
